# Generated by Django 6.0.1 on 2026-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_replacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
