# Generated by Django 6.0.1 on 2026-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_wishlist_confirmed_at_wishlist_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='out_for_delivery_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='shipped_at',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
